[package]
name = "diseasetracker"
version = "1.0.0"
description = "Disease Heat Map Tracker"

[dependencies]
"php/php" = "latest"

[fs]
"/app" = "."

[[command]]
name = "script"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
env = ["DOCUMENT_ROOT=/app"]
main-args = ["-S", "0.0.0.0:8080", "-t", "/app"]
